name: Train Model

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 14400
    steps:
      -
        uses: actions/checkout@v3
      -
        name: set up python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      -
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
      -
        name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
      - name: poetry install
        run: |
          poetry install --with=ubuntu,test
      - name: train model
        run: |
          poetry run train
